# Introduction to Data Science 2022

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' on Moodle.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* in *numpy.array()* Python.

In [7]:
import numpy as np

A = np.arange(10**7)
B = np.arange(10**7)
print(A)

[      0       1       2 ... 9999997 9999998 9999999]


2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [8]:
def add_with_for(A,B):
    C = np.ones(len(A), dtype=int)
    for i in range(len(A)):
        C[i] = (A[i] + B[i])
    return C

print(add_with_for(A,B))

[       0        2        4 ... 19999994 19999996 19999998]


3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [9]:
def np_add_arrays(array_1, array_2):
    return np.add(array_1, array_2)
print(np_add_arrays(A,B))

# In comparison with the for-loop, this is much faster

[       0        2        4 ... 19999994 19999996 19999998]


### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [ ]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

2. Create the following array:

In [ ]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [11]:
np.arange(100.).reshape(10,10)%2

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

3. Create the following array (D):

In [ ]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [12]:
D = np.eye(10) + 1
np.fill_diagonal(D,0)
D

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

4. Create the following array (E):

In [3]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
E = D[::-1]
E

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [17]:
DEProduct = np.dot(D,E)
DEDet = np.linalg.det(DEProduct)

DDet = np.linalg.det(D)
EDet = np.linalg.det(E)


-- *Use this markdown cell for your written answer* -- <br/>
No, this is not a coincidence! 

When it comes to any 2 square matrices, X and Y, of size nxn, det(XY) = det(X) * det(Y). That is because the determinant can be considered as the scaling factor for the transformation of a matrix. For this example, the Det(D) = -9, and Det(E) = 9. 

When multiplied, we get the following matrix: <br/>
<code>[[8. 8. 8. 8. 8. 8. 8. 8. 8. 9.]
 [8. 8. 8. 8. 8. 8. 8. 8. 9. 8.]
 [8. 8. 8. 8. 8. 8. 8. 9. 8. 8.]
 [8. 8. 8. 8. 8. 8. 9. 8. 8. 8.]
 [8. 8. 8. 8. 8. 9. 8. 8. 8. 8.]
 [8. 8. 8. 8. 9. 8. 8. 8. 8. 8.]
 [8. 8. 8. 9. 8. 8. 8. 8. 8. 8.]
 [8. 8. 9. 8. 8. 8. 8. 8. 8. 8.]
 [8. 9. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]</code>
 
Where Det(DE) = -81.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [6]:
from sklearn.datasets import fetch_california_housing;

cal_housing = fetch_california_housing()
cal_housing_data = cal_housing.data
cal_housing_features = cal_housing.feature_names

cal_housing_shape = cal_housing_data.shape
cal_housing_shape

(20640, 8)

2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [173]:
avgBedrmsIndex = cal_housing_features.index("AveBedrms")

avgBdrmsOverTwo = np.where(cal_housing_data[:,avgBedrmsIndex]>2)[0]
print(avgBdrmsOverTwo)
len(avgBdrmsOverTwo)
# print(len(avgBdrmsOverTwo), avgBdrmsOverTwo)

[  710  1023  1024  1030  1102  1233  1234  1235  1236  1238  1239  1240
  1566  1867  1871  1872  1879  1881  1889  1901  1906  1910  1911  1912
  1913  1914  1925  1926  1978  1979  2392  2395  2396  2397  2398  2510
  2511  2643  2656  2763  2768  2776  2778  3014  3086  3095  3258  3292
  3293  3313  3314  3334  3349  3350  9193  9423  9431  9451  9634  9669
  9671  9672  9675  9676  9678  9679  9680  9681  9682  9683 10067 10076
 10077 10078 10079 10080 10081 10082 10083 10084 10405 11705 11706 11707
 11708 11709 11710 11711 11713 11714 11715 11716 11717 11719 11720 11721
 11722 11723 11724 11725 11729 11831 11832 11833 11834 11847 11848 11849
 11850 11862 11865 11866 11867 11869 11870 12136 12303 12305 12306 12307
 12324 12325 12344 12349 12351 12354 12359 12361 12362 12366 12368 12371
 12372 12374 12376 12390 12392 12394 12396 12404 12405 12430 12446 12447
 13898 13900 13911 13912 13919 13920 13923 13924 13934 13935 13936 13937
 13939 13940 13941 13942 13943 13944 13945 13946 13

235

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [179]:
houseAgeIndex = cal_housing_features.index("HouseAge")

houseAgeOverOne = np.where((cal_housing_data[:,houseAgeIndex]>=1 )& (cal_housing_data[:,houseAgeIndex]<=3))[0]
len(houseAgeOverOne)

124

4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [214]:
populationIndex = cal_housing_features.index("Population")

# get all homes where median val > 25,000
medianHomesArray = np.where(cal_housing.target>.25)[0]

# get populations of the above rows
wantedPopulations = cal_housing_data[medianHomesArray,populationIndex]
meanSoltution = np.mean(wantedPopulations)
meanSoltution

1425.6833737275813

**Remember to submit your code on Moodle. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences.**

## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](http://deepyeti.ucsd.edu/jianmo/amazon/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file and access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user. 

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [220]:
import pandas as pd

df = pd.read_json('Automotive_5.json', lines=True)

reviewTextCol = df[['reviewText']]
reviewTextCol

reviewText
0        After I wrote the below review, the manufactur...
1        It sucks barely picks up anything definitely n...
2        Well to write a short one, it blew 2 fuses of ...
3        I have absolutely no memory of buying this but...
4                                     it ok it does it job
...                                                    ...
1711514                        Fast Shipping, Works Great!
1711515  Fit isn't great, relays are very hard to press...
1711516  I bought an auxiliary horn for my car and it n...
1711517  Way better than stock. Nice bright and white. ...
1711518  Great product fast shipping and awesome commun...

[1711519 rows x 1 columns]

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [253]:
reviewTextCol = df['reviewText']
lowerReviews = reviewTextCol.str.lower()
lowerReviews

0          after i wrote the below review, the manufactur...
1          it sucks barely picks up anything definitely n...
2          well to write a short one, it blew 2 fuses of ...
3          i have absolutely no memory of buying this but...
4                                       it ok it does it job
                                 ...                        
1711514                          fast shipping, works great!
1711515    fit isn't great, relays are very hard to press...
1711516    i bought an auxiliary horn for my car and it n...
1711517    way better than stock. nice bright and white. ...
1711518    great product fast shipping and awesome commun...
Name: reviewText, Length: 1711519, dtype: object

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxrZXZpbmJvdWdlfGd4OjY0MTNkZjJhOWIzODQ2Mzg) *(use the link to download a txt of english stopwords)*.

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [315]:
import string

def removeFunction(review):
    ''' reads in a string, removes
        punctuation & stop words. Returns str
    '''
    # remove punctuation
    noPunct = str(review).translate(str.maketrans('', '', string.punctuation))
    # split into list of words
    listOfWords = noPunct.split()
    # remove all stopwords
    updatedList = [word for word in listOfWords if word not in stopWords]
    # return the new string
    return ' '.join(updatedList)


In [319]:
strippedReviews = lowerReviews.apply(lambda x: removeFunction(x))
print(strippedReviews[0])

wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally charge sync cable hole charge side landscape position stand make sense im upgrading review 2 stars 4 stars rarely case user error star lack documentation manufacturer include directions encourage update photos amazon examples wood quality good sturdy stand im id stand facetime chats open office environment phone desk alerts notifications easily hope updated review helps original review throwing stand garbage crafted nice wood functional instructions product description confusing english poorly translated chinese iphone sits stand fine stand plug bottom plug stand blocks turn iphone plug top strange im hole back stand supposed included plastic feet instructions affixed bottom stand began wobble figure work thing post review im concerned box experience terrible recommend sample provided exchange honest review


4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the reviews, so that inflected forms are mapped to the base form. For example, in Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy-to-use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball).

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [328]:
from nltk.stem import *

stemmer = PorterStemmer()

def stemReview(review):
    ''' reads in a string, stems
        each word in the str
    '''
    # split into list of words
    listOfWords = review.split()
    # stem each word
    updatedList = [stemmer.stem(word) for word in listOfWords]
    # return the new string
    return ' '.join(updatedList)


strippedReviews = strippedReviews.apply(lambda x: stemReview(x))

print(strippedReviews)

0          wrote review manufactur contact explain curren...
1                  suck bare pick car pretti dont wast money
2               write short blew 2 fuse car appar demand 12v
3          absolut memori buy im review review stuff page...
4                                                        job
                                 ...                        
1711514                                 fast ship work great
1711515     fit isnt great relay hard press connector mechan
1711516    bought auxiliari horn car need run relay guy f...
1711517    stock nice bright white super easi instal top ...
1711518    great product fast ship awesom commun product ...
Name: reviewText, Length: 1711519, dtype: object


5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [358]:
overallRatingCol = df['overall']

# indices for positive & negative reviews
posIndices = np.where(overallRatingCol>=4)[0] # 0 4 5 8 9
negIndices = np.where(overallRatingCol<=2)[0] # 1 2 7 10 13

# use indices to select the preprocessed texts
posReviews = strippedReviews[posIndices] 
negReviews = strippedReviews[negIndices] 

# join the reviews with a \n character
posString = '\n'.join(posReviews)
negString = '\n'.join(negReviews)

# open and write the strings to the files
pos_file = open("pos.txt", "w")
neg_file = open("neg.txt", "w")

# write reviews to file
pos_file.write(posString)
neg_file.write(negString)

# close file
neg_file.close()
pos_file.close()

Having created two collections of positive and negative reviews respectively, you may wish to take a quick look to see how the review texts differ between them (positive vs negative). Keep these files, as we will be using this data later to experiment with machine learning methods.

**Remember to submit your code on Moodle. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. No need to submit the text files.**